version: "3"
services:
  backend:
    image: your_dockerhub_username/backend:latest
    ports:
      - "8000:8000"
    build: .
    environment:
      - DEBUG=True
    volumes:
      - .:/app
  
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # command: ["sh", "-c", "mkdir -p /etc/nginx/sites-enabled && ln -s /etc/nginx/sites-available/studymate.conf /etc/nginx/sites-enabled/studymate.conf && nginx -g 'daemon off;'"]
    depends_on:
      - backend
    
