# Generated by Django 5.1.4 on 2024-12-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_tools', '0002_answer_card_course_question_delete_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_of_creation',
        ),
    ]
