name: deploy
run-name: Deploy to AWS ECS instance
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Debug Directory Structure
      run: ls -R
    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Create .env File
      run: |
        echo "GEMNI_API_KEY=${{ secrets.GEMNI_API_KEY }}" >> studymate/.env
        echo "HOSTS=${{ secrets.HOSTS }}" >> studymate/.env
    - name: Build docker image
      run: docker build -t danielyilma/studymate:latest .
    - name: Push to Dockerhub
      run: docker push danielyilma/studymate:latest
