name: deploy
run-name: Deploy to AWS ECS instance
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build docker image
      run: docker build -t studymate -f studymate/Dockerfile studymate/
    - name: Push to Dockerhub
      run: docker push danielyilma/studymate:latest
